//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compilador.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compilador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _036_floppy_disk {
            get {
                object obj = ResourceManager.GetObject("_036_floppy_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _066_plus {
            get {
                object obj = ResourceManager.GetObject("_066_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _090_upload {
            get {
                object obj = ResourceManager.GetObject("_090_upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR01,Se esperaba un simbolo diferente u otra terminacion.
        ///ERROR02,La constante numerica incluye simbolos ajenos a los permitidos.
        ///ERROR03,El operador logico indicado no existe.
        ///ERROR04,El operador aritmetico indicado no existe.
        ///ERROR05,El operador relacional indicado no existe.
        ///ERROR06,No existe una instrucción con la estructura indicada.
        ///ERROR07,El identificador no cumple con las reglas definidas.
        ///ERROR08,Se esperaba otro simbolo o fin para la cadena de texto
        ///ERROR11,Asignacion de un valor difer [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Errores {
            get {
                return ResourceManager.GetString("Errores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S,PR01,SENTENCIA,PR02,,,,,
        ///SENTENCIA,SENTENCIA,SENTENCIA,,,,,,
        ///SENTENCIA,ASENT,,,,,,,
        ///SENTENCIA,IFSIMPLE,,,,,,,
        ///SENTENCIA,IFSIMPLE,PR06,BLOQUE,,,,,
        ///IFSIMPLE,IF,BLOQUE,,,,,,
        ///IF,PR05,CAES02,ID,CAES13,,,,
        ///IF,PR05,CAES02,BOOL,CAES13,,,,
        ///SENTENCIA,WHILE,BLOQUE,,,,,,
        ///SENTENCIA,DO,,,,,,,
        ///DO,PR13,BLOQUE,WHILE,,,,,
        ///WHILE,PR11,CAES02,BOOL,CAES13,,,,
        ///SENTENCIA,FOR,BLOQUE,,,,,,
        ///FOR,PR12,CAES02,ASENT,CAES11,BOOL,CAES11,ASENT,CAES13
        ///SENTENCIA,SWITCH,,,,,,,
        ///SWITCH,SWENTRADA,CAES14,SWCUERPO,CAES15,,,,
        ///SWENT [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Gramaticas {
            get {
                return ResourceManager.GetString("Gramaticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estados,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,0,1,2,3,4,5,6,7,8,9,+,-,*,/,%,^,?,&lt;,=,&gt;,&amp;,|,ñ,Ñ,á,é,í,ó,ü,(,),#,CS,CD,$,¿,?,¡,!,{,},:,CM,.,;,FDC,Categoria
        ///0,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,210,1,9,24,37,55,210,63,69,210,210,76,81,210,210,90,210,101,108,210,210,230,210,210,210,210,121,121,121,121,121,121,121,121,121,121,119,120,148,150,154,152,156,133,130,126,139,141,169,16 [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Matriz {
            get {
                return ResourceManager.GetString("Matriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PR19 ID01.Flot OPAS CNR01 
        ///
        ///PR17 ID02.Ent OPAS CNE02 OPAR1 ID01.Flot 
        ///
        ///PR17 ID02.Ent OPAS ID01.Flot OPAR1 CNE02 
        ///
        ///PR17 ID02.Ent OPAS ID01.Flot OPAR1 ID01.Flot .
        /// </summary>
        public static string Tokens {
            get {
                return ResourceManager.GetString("Tokens", resourceCulture);
            }
        }
    }
}
